name: alu_tracker
description: ALU Tracker for Babin and Mohuu
publish_to: none
version: 0.1.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  geolocator: ^13.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  local_auth: ^2.3.0
  shared_preferences: ^2.2.0
  battery_plus: ^6.0.0
  vibration: ^2.0.0
  call_log: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_sms_inbox: ^1.0.4
  permission_handler: ^11.3.0
flutter:
  uses-material-design: true
